### ISSUE TITLE
[Documentation] Provide more examples

### ISSUE THREAD

**Issue by simaki** [simaki/epymetheus#28]

**Comment by simaki** [comment]
* buy and hold

**Comment by simaki** [comment]
* sell in May

**Comment by simaki** [comment]
* january effect

**Comment by jkravets1** [comment]
Can you make an example with a moving average crossover for every asset in the universe?

**Comment by simaki** [comment]
That's nice to have, thank you so much for your suggestion.

But unfortunately, I'm afraid I don't have enough time to provide that.
Pull-requests are welcomed. Thanks though!
