### ISSUE TITLE
[QUESTION] Adding csv data to universe

### ISSUE THREAD

**Issue by shishaboy** [simaki/epymetheus#40]
Im having trouble adding csv data with the correct time format, could you post an example?

[2021_backtest-Copy1.pdf](https://github.com/simaki/epymetheus/files/5613253/2021_backtest-Copy1.pdf)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
pandas/_libs/index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 699321600000000000

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2888             try:
-> 2889                 return self._engine.get_loc(casted_key)
   2890             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

KeyError: Timestamp('1992-02-29 00:00:00')

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py in get_loc(self, key, method, tolerance)
    624         try:
--> 625             return Index.get_loc(self, key, method, tolerance)
    626         except KeyError as err:

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2890             except KeyError as err:
-> 2891                 raise KeyError(key) from err
   2892 

KeyError: Timestamp('1992-02-29 00:00:00')

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-58-867c3ddadeaf> in <module>
----> 1 strategy.run(universe)

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/epymetheus/strategy/strategy.py in run(self, universe, metrics, budget, verbose)
    176 
    177         self.universe = universe
--> 178         self.__generate_trades(universe=universe, verbose=verbose)
    179         self.__execute_trades(universe=universe, verbose=verbose)
    180 

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/epymetheus/strategy/strategy.py in __generate_trades(self, universe, verbose)
    218                     yield trade
    219 
--> 220         self.trades = list(iter_trades(verbose))
    221 
    222         if len(self.trades) == 0:

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/epymetheus/strategy/strategy.py in iter_trades(verbose)
    207             if verbose:
    208                 begin_time = time()
--> 209                 for i, trade in enumerate(self.logic(universe) or []):
    210                     print(
    211                         f"\rGenerating {i + 1} trades " f"({trade.open_bar}) ... ",

<ipython-input-3-5d3ca96ea9b6> in logic(self, universe)
     57 
     58         for open_date in date_range[1:]:
---> 59             assets = self.sorted_assets(universe, open_date)
     60             for asset_l, asset_s in zip(assets[-n_trade:][::-1], assets[:n_trade]):
     61                 lot_l = +self.l_price / universe.prices.at[open_date, asset_l]

<ipython-input-3-5d3ca96ea9b6> in sorted_assets(universe, open_date)
     46 
     47         prices_now = universe.prices.loc[open_date]
---> 48         prices_bef = universe.prices.loc[open_date - DateOffset(months=1)]
     49         onemonth_returns = prices_now - prices_bef
     50 

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    877 
    878             maybe_callable = com.apply_if_callable(key, self.obj)
--> 879             return self._getitem_axis(maybe_callable, axis=axis)
    880 
    881     def _is_scalar_access(self, key: Tuple):

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1108         # fall thru to straight lookup
   1109         self._validate_key(key, axis)
-> 1110         return self._get_label(key, axis=axis)
   1111 
   1112     def _get_slice_axis(self, slice_obj: slice, axis: int):

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/pandas/core/indexing.py in _get_label(self, label, axis)
   1057     def _get_label(self, label, axis: int):
   1058         # GH#5667 this will fail if the label is not present in the axis.
-> 1059         return self.obj.xs(label, axis=axis)
   1060 
   1061     def _handle_lowerdim_multi_index_axis0(self, tup: Tuple):

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/pandas/core/generic.py in xs(self, key, axis, level, drop_level)
   3480             loc, new_index = self.index.get_loc_level(key, drop_level=drop_level)
   3481         else:
-> 3482             loc = self.index.get_loc(key)
   3483 
   3484             if isinstance(loc, np.ndarray):

~/miniconda2/envs/mypython3.7/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py in get_loc(self, key, method, tolerance)
    625             return Index.get_loc(self, key, method, tolerance)
    626         except KeyError as err:
--> 627             raise KeyError(orig_key) from err
    628 
    629     def _maybe_cast_for_get_loc(self, key) -> Timestamp:

KeyError: Timestamp('1992-02-29 00:00:00')

**Comment by simaki** [comment]
First of all, thank you so much for using this.
I'm really glad to know that.

Well just maybe, 1992-02-29 is Saturday and so the row may not be there (I'm not sure though).

**Comment by simaki** [comment]
@shishaboy 
Hi, have you successfully solved your problem, or is there something I can help with?
If you have solved it, I'm closing this issue.

**Comment by jkravets1** [comment]
not yet

**Comment by simaki** [comment]
@shishaboy 
Oh, I got it.
Is there something I can give help with?

**Comment by jkravets1** [comment]
I've been busy with graduate school i will come back to it at the end of the month. Thanks!

**Comment by simaki** [comment]
Close in the hope that the problem has been resolved.
