### ISSUE TITLE
[ENH] Do not check NA, duplicate by default

### ISSUE THREAD

**Issue by simaki** [simaki/epymetheus#41]
https://github.com/simaki/epymetheus/blob/f10dc28d5a409b23f3f034c72d5999790dbdb8f0/epymetheus/universe/universe.py#L35

* Make a parameter `Universe(..., check_prices=False)` 
* Only if `check_prices=True`, run `__check_price`.

cf
https://github.com/shishaboy/epymetheus/commit/d8916b20c6b79e86e5aadb39c7c01a582659f03b

**Comment by jkravets1** [comment]
I'll make some pull requests after Dec 20, thanks for the replying!

**Comment by simaki** [comment]
solved by #114
